print('=' * 50)
times = ('Flamengo', 'Internacional', 'Atlético-MG', 'São Paulo', 'Fluminense', 'Grêmio', 'Palmeiras', 'Santos', 'Athletico-PR', 'Bragantino', 'Ceará-SC', 'Atlético-GO', 'Bahia', 'Sport Recife', 'Fortaleza', 'Vasco da Gama', 'Goiás', 'Coritiba', 'Botafogo')
print(f'Lista de times do Brasileirão {times}')
print('=' * 50)
print(f'Os 5 primeiros são {times[0:5]}')
print('=' * 50)
print(f'Os últimos são {times[15:20]}')
print('=' * 50)
print(f'Times em ordem alfabética: {sorted (times)}')
print('=' * 50)
print(f'O {times[7]} está na 8ª posição')